services:
  # Tor Hidden Service with Custom .onion Address Generation
  tor:
    build:
      context: ./docker/tor
      dockerfile: Dockerfile
    environment:
      - ONION_PREFIX=${ONION_PREFIX:-san}
      - MAX_ATTEMPTS=${MAX_ATTEMPTS:-1000000}
    volumes:
      - tor_data:/var/lib/tor
      - shared_data:/shared
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - nginx
      - backend
      - db
      - ipfs
      - icecast
      - redis
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9050"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Self-hosted IPFS Node
  ipfs:
    build:
      context: ./docker/ipfs
      dockerfile: Dockerfile
    environment:
      - IPFS_PATH=/data/ipfs
    volumes:
      - ipfs_data:/data/ipfs
      - ipfs_staging:/export
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ipfs", "id"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Enhanced Backend with Security Improvements
  backend:
    build:
      context: ./backend
      dockerfile: ../infra/Dockerfile.backend
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://san2stic:secure_password_change_this@db:5432/san2stic
      - JWT_SECRET=your_jwt_secret_change_this_to_something_secure
      - IPFS_HOST=ipfs
      - IPFS_PORT=5001
      - IPFS_PROTOCOL=http
      - IPFS_GATEWAY_URL=http://ipfs:8080/ipfs/
      - ICECAST_URL=http://icecast:8000
      - ICECAST_MOUNT=/stream
      - PORT=4000
    volumes:
      - shared_data:/shared
    depends_on:
      db:
        condition: service_healthy
      ipfs:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Enhanced Icecast Streaming Server
  icecast:
    build:
      context: ./infra
      dockerfile: Dockerfile.icecast
    environment:
      - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD:-secure_source_password}
      - ICECAST_RELAY_PASSWORD=${ICECAST_RELAY_PASSWORD:-secure_relay_password}
      - ICECAST_ADMIN_USER=${ICECAST_ADMIN_USER:-admin}
      - ICECAST_ADMIN_PASSWORD=${ICECAST_ADMIN_PASSWORD:-secure_admin_password}
      - ICECAST_HOSTNAME=${ICECAST_HOSTNAME:-localhost}
    volumes:
      - ./infra/icecast.xml:/etc/icecast2/icecast.xml
      - icecast_logs:/var/log/icecast
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status.xsl"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy with Security Headers
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_cache:/var/cache/nginx
      - nginx_logs:/var/log/nginx
      - shared_data:/shared
    depends_on:
      - backend
      - icecast
      - ipfs
      - frontend
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database with Performance Tuning
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=san2stic
      - POSTGRES_PASSWORD=secure_password_change_this
      - POSTGRES_DB=san2stic
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U san2stic"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200

  # Redis Cache for Performance
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  # Monitoring and Health Checks
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  ipfs_data:
    driver: local
  ipfs_staging:
    driver: local
  tor_data:
    driver: local
  shared_data:
    driver: local
  nginx_cache:
    driver: local
  nginx_logs:
    driver: local
  icecast_logs:
    driver: local
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
