apiVersion: v1
kind: Secret
metadata:
  name: backend-secret # Nom du Secret pour le backend
  labels:
    app: san2stic
    component: backend
type: Opaque
data:
  # Clé JWT_SECRET. Remplacez la valeur par votre secret encodé en Base64.
  # Pour encoder : echo -n 'votre_jwt_secret_reel' | base64
  JWT_SECRET: "eW91cl9qd3Rfc2VjcmV0X2Jhc2U2NF9lbmNvZGVk" # Placeholder pour "your_jwt_secret_base64_encoded"