apiVersion: v1
kind: Service
metadata:
  name: san2stic-backend-svc # Nom du service
  labels:
    app: san2stic
    component: backend
spec:
  type: ClusterIP # Expose le service sur une IP interne au cluster
  selector:
    app: san2stic      # Doit correspondre aux labels des pods du Deployment
    component: backend
  ports:
    - protocol: TCP
      port: 80           # Port sur lequel le service est exposé DANS LE CLUSTER
      targetPort: 4000   # Port sur lequel les pods du backend écoutent (containerPort)