apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: san2stic
    component: backend
data:
  # Configuration Google Cloud Storage
  GCS_PROJECT_ID: "your_project_id" # REMPLACEZ par votre ID de projet GCP
  GCS_BUCKET_NAME: "your_bucket_name" # REMPLACEZ par votre nom de bucket GCS

  # Configuration Icecast (utilisera le nom du service Kubernetes d'Icecast)
  ICECAST_URL: "http://san2stic-icecast-svc:8000" # san2stic-icecast-svc est le nom attendu du service K8s pour Icecast
  ICECAST_MOUNT: "/stream"

  # Configuration de la base de données (utilisera le nom du service Kubernetes de PostgreSQL)
  # Ces valeurs seront utilisées par l'application backend pour se connecter à PostgreSQL.
  DB_HOST: "san2stic-postgresql-svc" # san2stic-postgresql-svc est le nom attendu du service K8s pour PostgreSQL
  DB_NAME: "san2stic_db"          # REMPLACEZ par le nom de votre base de données
  DB_PORT: "5432"                 # Port standard de PostgreSQL