apiVersion: v1
kind: Secret
metadata:
  name: gcp-keyfile-secret # Nom du Secret pour la clé GCP, référencé dans le Deployment
  labels:
    app: san2stic
    component: backend
type: Opaque
data:
  # La clé ici (gcp-keyfile.json) sera le nom du fichier monté dans le pod.
  # Remplacez la valeur par le contenu de votre fichier gcp-keyfile.json encodé en Base64.
  # Pour encoder : cat /chemin/vers/votre/gcp-keyfile.json | base64
  gcp-keyfile.json: "YmFzZTY0X2VuY29kZWRfZ2NwX2tleWZpbGVfanNvbl9jb250ZW50" # Placeholder