apiVersion: v1
kind: Secret
metadata:
  name: icecast-secret # Nom référencé dans icecast-deployment.yaml
  labels:
    app: san2stic
    component: icecast
type: Opaque
data:
  # Remplacez les valeurs suivantes par vos mots de passe réels encodés en Base64.
  # echo -n 'votre_mot_de_passe_source' | base64
  source_password: "Y2hhbmdlbWVfc291cmNlX3Bhc3N3b3JkX2Jhc2U2NA==" # Placeholder pour changeme_source_password

  # echo -n 'votre_mot_de_passe_relais' | base64
  relay_password: "Y2hhbmdlbWVfcmVsYXlfcGFzc3dvcmRfYmFzZTY0" # Placeholder pour changeme_relay_password

  # echo -n 'votre_utilisateur_admin_icecast' | base64
  admin_username: "YWRtaW5fYmFzZTY0" # Placeholder pour admin

  # echo -n 'votre_mot_de_passe_admin_icecast' | base64
  admin_password: "Y2hhbmdlbWVfYWRtaW5fcGFzc3dvcmRfYmFzZTY0" # Placeholder pour changeme_admin_password