apiVersion: v1
kind: ConfigMap
metadata:
  name: icecast-config # Nom référencé dans icecast-deployment.yaml
  labels:
    app: san2stic
    component: icecast
data:
  # La valeur pour icecast_hostname.
  # Pour une exposition externe via LoadBalancer, le véritable hostname externe
  # sera l'IP du LoadBalancer. Cette valeur peut être utilisée pour des configurations internes
  # ou si l'application backend a besoin de connaître le nom du service Icecast.
  icecast_hostname: "san2stic-icecast-svc" # Nom du service Kubernetes pour Icecast

  # Contenu du fichier icecast.xml
  # Les mots de passe ici sont des placeholders. L'image Icecast est supposée
  # utiliser les variables d'environnement (ICECAST_SOURCE_PASSWORD, etc.)
  # injectées depuis le Secret pour surcharger ces valeurs ou les utiliser.
  icecast.xml: |
    <icecast>
      <location>Earth</location>
      <admin>admin@san2stic.example.com</admin>
      <!-- <hostname> à 0.0.0.0 permet d'écouter sur toutes les interfaces du pod -->
      <hostname>0.0.0.0</hostname>
      <limits>
        <clients>100</clients>
        <sources>2</sources>
        <queue-size>524288</queue-size>
        <client-timeout>30</client-timeout>
      </limits>
      <authentication>
        <!-- Ces valeurs devraient être surchargées par les variables d'environnement du Secret -->
        <source-password>changeme_source_password</source-password>
        <relay-password>changeme_relay_password</relay-password>
        <admin-user>admin</admin-user>
        <admin-password>changeme_admin_password</admin-password>
      </authentication>
      <listen-socket>
        <port>8000</port>
      </listen-socket>
      <mount>
        <mount-name>/stream</mount-name>
        <!-- Ce mot de passe devrait également être géré via Secret si possible,
             sinon il doit être défini ici ou la variable ICECAST_SOURCE_PASSWORD est utilisée.
             Pour l'instant, on suppose que ICECAST_SOURCE_PASSWORD couvre ce cas. -->
        <password>changeme_stream_source_password</password>
        <max-listeners>100</max-listeners>
      </mount>
    </icecast>