apiVersion: v1
kind: Service
metadata:
  name: san2stic-icecast-svc # Nom du service, utilisé dans backend-configmap.yaml
  labels:
    app: san2stic
    component: icecast
spec:
  type: LoadBalancer # Expose le service à l'extérieur du cluster via un Load Balancer GCP
  selector:
    app: san2stic
    component: icecast
  ports:
    - protocol: TCP
      port: 8000       # Port exposé par le Load Balancer
      targetPort: 8000   # Port sur lequel les pods Icecast écoutent (containerPort)
      name: icecast-tcp