apiVersion: apps/v1
kind: Deployment
metadata:
  name: san2stic-icecast
  labels:
    app: san2stic
    component: icecast
spec:
  replicas: 1 # Icecast est généralement stateful pour les streams actifs, commencer avec 1 replica. Peut être augmenté si la configuration le permet.
  selector:
    matchLabels:
      app: san2stic
      component: icecast
  template:
    metadata:
      labels:
        app: san2stic
        component: icecast
    spec:
      containers:
        - name: icecast
          image: bucharestgold/icecast:latest
          ports:
            - containerPort: 8000
              name: icecast-port
          env:
            # Ces variables sont souvent utilisées pour surcharger les valeurs dans icecast.xml
            # ou par un script d'entrée dans l'image Docker.
            # Elles seront chargées depuis un Secret.
            - name: ICECAST_SOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icecast-secret
                  key: source_password
            - name: ICECAST_RELAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icecast-secret
                  key: relay_password
            - name: ICECAST_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: icecast-secret
                  key: admin_username
            - name: ICECAST_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icecast-secret
                  key: admin_password
            - name: ICECAST_HOSTNAME # Sera le nom du service K8s ou l'IP externe
              valueFrom:
                configMapKeyRef:
                  name: icecast-config
                  key: icecast_hostname
          volumeMounts:
            - name: icecast-config-volume
              mountPath: /etc/icecast2/icecast.xml # Chemin attendu par l'image Icecast
              subPath: icecast.xml # Monte uniquement le fichier icecast.xml du ConfigMap
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: icecast-config-volume
          configMap:
            name: icecast-config # Nom du ConfigMap contenant icecast.xml