apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret # Nom référencé dans postgresql-statefulset.yaml et backend-deployment.yaml
  labels:
    app: san2stic
    component: postgresql
type: Opaque # Type par défaut pour les secrets
data:
  # Remplacez les valeurs suivantes par vos identifiants réels encodés en Base64.

  # echo -n 'votre_utilisateur_postgres' | base64
  postgresql-user: "c2FuMnN0aWNfdXNlcg==" # Placeholder pour "san2stic_user"

  # echo -n 'votre_mot_de_passe_postgres_tres_securise' | base64
  postgresql-password: "c2FuMnN0aWNfcGFzc3dvcmQ=" # Placeholder pour "san2stic_password"

  # echo -n 'votre_nom_de_db_postgres' | base64
  postgresql-db: "c2FuMnN0aWNfZGI=" # Placeholder pour "san2stic_db"