apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: san2stic-postgresql
  labels:
    app: san2stic
    component: postgresql
spec:
  serviceName: "san2stic-postgresql-svc" # Nom du Service Headless à créer pour ce StatefulSet
  replicas: 1 # Pour une base de données simple, commencez avec 1 replica. La réplication est plus complexe.
  selector:
    matchLabels:
      app: san2stic
      component: postgresql
  template:
    metadata:
      labels:
        app: san2stic
        component: postgresql
    spec:
      terminationGracePeriodSeconds: 10 # Temps pour que le pod s'arrête proprement
      containers:
        - name: postgresql
          image: postgres:13-alpine
          ports:
            - containerPort: 5432
              name: postgresql
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret # Nom du Secret pour les identifiants PostgreSQL
                  key: postgresql-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgresql-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef: # Ou ConfigMap si le nom de la DB n'est pas sensible
                  name: postgresql-secret
                  key: postgresql-db
            - name: PGDATA # Définit le répertoire des données PostgreSQL
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgresql-data # Nom du PersistentVolumeClaim
              mountPath: /var/lib/postgresql/data # Chemin où les données seront stockées
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m" # 0.25 vCPU
            limits:
              memory: "1Gi"
              cpu: "500m" # 0.5 vCPU
  volumeClaimTemplates: # Crée un PersistentVolumeClaim pour chaque pod
    - metadata:
        name: postgresql-data # Le nom du PVC sera <metadata.name>-<pod_name>
      spec:
        accessModes: ["ReadWriteOnce"] # Le volume peut être monté en lecture-écriture par un seul nœud
        resources:
          requests:
            storage: 10Gi # Taille du disque persistant (ajustez selon vos besoins)
        # storageClassName: "standard" # Optionnel: spécifiez une classe de stockage si nécessaire (GCP en a une par défaut)