apiVersion: v1
kind: Service
metadata:
  name: san2stic-postgresql-svc # Nom du service, référencé dans backend-configmap.yaml et le StatefulSet
  labels:
    app: san2stic
    component: postgresql
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgresql
  clusterIP: None # Crée un service "headless" pour le StatefulSet
  selector:
    app: san2stic
    component: postgresql # Doit correspondre aux labels des pods du StatefulSet