apiVersion: v1
kind: ConfigMap
metadata:
  name: icecast-config
  namespace: san2stic
data:
  icecast.xml: |
    <icecast>
        <location>San2Stic Platform</location>
        <admin>admin@san2stic.com</admin>
        <hostname>icecast.san2stic.com</hostname>
        <limits>
            <clients>1000</clients>
            <sources>10</sources>
            <threadpool>5</threadpool>
            <queue-size>524288</queue-size>
            <client-timeout>30</client-timeout>
            <header-timeout>15</header-timeout>
            <source-timeout>10</source-timeout>
            <burst-on-connect>1</burst-on-connect>
            <burst-size>65535</burst-size>
        </limits>
        <authentication>
            <source-password>hackme</source-password>
            <relay-password>hackme</relay-password>
            <admin-user>admin</admin-user>
            <admin-password>hackme</admin-password>
        </authentication>
        <listen-socket>
            <port>8000</port>
        </listen-socket>
        <fileserve>1</fileserve>
        <paths>
            <basedir>/usr/share/icecast</basedir>
            <logdir>/var/log/icecast</logdir>
            <webroot>/usr/share/icecast/web</webroot>
            <adminroot>/usr/share/icecast/admin</adminroot>
            <alias source="/" destination="/status.xsl"/>
        </paths>
        <logging>
            <accesslog>access.log</accesslog>
            <errorlog>error.log</errorlog>
            <loglevel>3</loglevel>
            <logsize>10000</logsize>
        </logging>
        <security>
            <chroot>0</chroot>
        </security>
    </icecast>
---
apiVersion: v1
kind: Secret
metadata:
  name: icecast-secrets
  namespace: san2stic
type: Opaque
stringData:
  source-password: "change-this-source-password"
  relay-password: "change-this-relay-password"
  admin-password: "change-this-admin-password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: icecast-deployment
  namespace: san2stic
  labels:
    app: icecast
    component: streaming
spec:
  replicas: 2
  selector:
    matchLabels:
      app: icecast
  template:
    metadata:
      labels:
        app: icecast
        component: streaming
    spec:
      containers:
      - name: icecast
        image: ghcr.io/epicsandev/san2stic---maps/icecast:latest
        ports:
        - containerPort: 8000
          name: icecast
        volumeMounts:
        - name: icecast-config
          mountPath: /etc/icecast.xml
          subPath: icecast.xml
        - name: icecast-logs
          mountPath: /var/log/icecast
        livenessProbe:
          httpGet:
            path: /status.xsl
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /status.xsl
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: icecast-config
        configMap:
          name: icecast-config
      - name: icecast-logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: icecast-service
  namespace: san2stic
  labels:
    app: icecast
spec:
  selector:
    app: icecast
  ports:
  - port: 8000
    targetPort: 8000
    name: icecast
  type: LoadBalancer
  # For production, consider using a static IP
  # loadBalancerIP: "YOUR-STATIC-IP"
---
# Optional: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: icecast-hpa
  namespace: san2stic
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: icecast-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80