apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference to base
bases:
  - ../../

# Environment-specific name suffix
nameSuffix: -production

# Production-ready images with specific tags
images:
  - name: ghcr.io/epicsandev/san2stic---maps/backend
    newTag: latest
  - name: ghcr.io/epicsandev/san2stic---maps/icecast
    newTag: latest

# Patches for production environment
patchesStrategicMerge:
  - backend-production-patch.yaml
  - postgresql-production-patch.yaml

# Environment-specific labels
commonLabels:
  environment: production

# Production-specific replicas
replicas:
  - name: backend-deployment
    count: 3
  - name: icecast-deployment
    count: 2