name: Deploy Application

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    environment: ${{ github.event.inputs.environment || 'staging' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Use dynamic docker-compose
      run: |
        echo "✅ Using repository's docker-compose.prod.yml"
        cat docker-compose.yml
    - name: Deploy to ${{ github.event.inputs.environment || 'staging' }}
      run: |
        echo "🚀 Deploying to ${{ github.event.inputs.environment || 'staging' }}"
        echo "Images used:"
        echo "- Backend: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest"
        echo "- Frontend: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest"
        echo "- Nginx: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/nginx:latest"
        echo "- Tor: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tor:latest"
        echo "- IPFS: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/ipfs:latest"
        echo "- Icecast: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/icecast:latest"
        
        # Here you would add your actual deployment commands
        # For example, if deploying to a remote server:
        # scp docker-compose.prod.yml user@server:/path/to/app/
        # ssh user@server "cd /path/to/app && docker-compose -f docker-compose.prod.yml up -d"
        
        echo "✅ Deployment completed successfully!"

    - name: Upload production compose file
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-prod-${{ github.event.inputs.environment || 'staging' }}
        path: docker-compose.prod.yml
        retention-days: 30